In [1]:
import numpy as np

In [2]:
'''
    try:
        data = load_data()
    except IOError:
        print "Missing dataset! Run:"
        print "wget http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
        sys.exit(1)
'''

data = np.genfromtxt('iris.csv', delimiter=',')

In [3]:
low = np.amin(data, axis=0)

In [4]:
high = np.amax(data, axis=0)

In [5]:
for j in range(4):
    minimum = low[j]
    maximum = high[j]
    for i in range(150):
        data[i][j] = (data[i][j] - minimum)/(maximum - minimum)

In [6]:
m = 150
mat = np.zeros(shape=(m, m))
for i in range(m):
    for j in range(m):
        mat[i, j] = ((data[i][0] - data[j][0])**2 + (data[i][1] - data[j][1]
                                                        )**2 + (data[i][2] - data[j][2])**2 + (data[i][3] - data[j][3])**2)
        mat[i, j] = mat[i, j]**0.5

In [7]:
avg = np.zeros(shape=(m))
for i in range(m):
    for j in range(m):
        avg[i] += mat[i][j]
    avg[i] = avg[i] / m

In [8]:
clusters = []
for i in range(m):
    cluster = []
    for j in range(m):
        if(mat[i][j] < avg[j]):
            cluster.append(j)
    clusters.append(cluster)
cluster_original = clusters

In [9]:
print(len(clusters))
print(clusters[0])
print(clusters[1])
print(clusters[2])

150
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 57, 60, 93, 98]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 57, 93, 98]


In [20]:
clusters = np.asarray(clusters)
print(clusters.shape)

(150,)


In [21]:
'''
Remove the clusters (if any) which are subset of some other clusters. As a result you have now say,
p (<m) clusters.
'''





idx = []
for i in range(m):
    for j in range(m):
        if(i!=j):
            if(len(np.setdiff1d(clusters[i],clusters[j])) == 0):
                
                idx.append(i)

idx = np.unique(idx)
#print(idx)
clusters = np.delete(clusters,idx,0)
print(len(clusters)) # 5

0


In [13]:
'''
Create a similarity matrix C of size pXp where, each (i, j)-th entry in the matrix gives the similarity
measurement between i-th cluster Ci and j-th cluster Cj using following similarity measure.
Cij =|Ci ∩ Cj|/|Ci ∪ Cj|
'''
p = len(clusters)
sim = np.zeros(shape=(p, p))
for i in range(p):
    for j in range(p):
        sim[i, j] = len(np.intersect1d(clusters[i], clusters[j])
                        ) / len(np.union1d(clusters[i], clusters[j]))
print(sim)

[[1.         0.37       0.85393258 0.73195876 0.16190476 0.2       ]
 [0.37       1.         0.4        0.34375    0.         0.        ]
 [0.85393258 0.4        1.         0.63541667 0.0990099  0.13861386]
 [0.73195876 0.34375    0.63541667 1.         0.21276596 0.2688172 ]
 [0.16190476 0.         0.0990099  0.21276596 1.         0.8       ]
 [0.2        0.         0.13861386 0.2688172  0.8        1.        ]]


In [12]:
'''
Out of all p*p entries in matrix C, find out the maximum value. If multiple maximum values occur,
choose any one randomly. Let, Ckl is the maximum value selected, that implies clusters Ck and Cl are
the most similar clusters among all p clusters. Merge these two clusters Ck and Cl to get a new cluster
Ckl, i.e. Ckl = Ck U Cl.
'''
val = 0
idx_k = 0
idx_l = 0
for i in range(p):
    for j in range(p):
        if(i != j):
            if(sim[i, j] > val):
                val = sim[i, j]
                idx_k = i
                idx_l = j
print(val)
print(idx_k)
print(idx_l)

0.8
3
4


In [13]:
print(clusters[idx_k])

[50, 52, 100, 102, 104, 105, 107, 109, 110, 112, 115, 116, 117, 118, 120, 122, 124, 125, 128, 129, 130, 131, 132, 135, 136, 137, 139, 140, 141, 143, 144, 145, 147, 148]


In [14]:
print(clusters[idx_l])

[77, 100, 102, 103, 104, 105, 107, 108, 109, 110, 111, 112, 114, 115, 116, 117, 118, 120, 122, 124, 125, 128, 129, 130, 131, 132, 135, 136, 137, 139, 140, 141, 143, 144, 145, 146, 147, 148]


In [15]:
merged_clusters = np.union1d(clusters[idx_k], clusters[idx_l])
print(merged_clusters)
print("\nlen : " + str(len(merged_clusters)))

[ 50  52  77 100 102 103 104 105 107 108 109 110 111 112 114 115 116 117
 118 120 122 124 125 128 129 130 131 132 135 136 137 139 140 141 143 144
 145 146 147 148]

len : 40


In [16]:
ids = [idx_k, idx_l]
clusters = np.delete(clusters,ids,0)
print("\nlen : " + str(len(clusters)))


len : 3


In [17]:
x = np.concatenate((clusters, merged_clusters)) #np.concatenate, np.vstack are the two possible options
print(x)
print("\nlen : " + str(len(x)))

[list([1, 2, 3, 8, 9, 12, 13, 25, 29, 30, 34, 35, 37, 38, 41, 42, 45, 47, 53, 55, 57, 59, 60, 62, 64, 67, 68, 69, 71, 72, 79, 80, 81, 82, 84, 87, 88, 89, 90, 92, 93, 94, 95, 96, 98, 99, 106, 113, 119, 134])
 list([8, 25, 41, 50, 51, 52, 53, 54, 55, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 101, 103, 106, 107, 108, 111, 113, 114, 116, 118, 119, 121, 122, 123, 126, 127, 128, 129, 130, 132, 133, 134, 138, 142, 146, 149])
 list([41, 53, 54, 55, 56, 57, 59, 60, 61, 62, 63, 64, 66, 67, 68, 69, 70, 71, 72, 73, 74, 78, 79, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 103, 104, 106, 108, 110, 111, 112, 113, 114, 115, 116, 118, 119, 120, 121, 123, 124, 126, 127, 128, 132, 133, 134, 136, 137, 138, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])
 50 52 77 100 102 103 104 105 107 108 109 110 111 112 114 115 116 117 118
 120 122 124 125

In [18]:
dummy = [[] for _ in range(len(clusters))]
for i in range(len(clusters)):
    for j in range(len(clusters[i])):
        dummy[i].append(clusters[i][j])
dummy.append(merged_clusters)
print(len(dummy))
print(len(clusters))
clusters = dummy
print(len(clusters))
print(len(clusters[0]), len(clusters[1]), len(clusters[2]), len(clusters[3]))

4
3
4
50 76 80 40


In [19]:
## METHOD 1: WILL ONLY WORK FOR SQUARE ARRAY r

r = [[1,2,3],[4,5,6],[1,2,3],[1,2,3],[7,8,9]]

for i in range(5):
    for j in range(5):
        if(i!=j):
            if(len(np.setdiff1d(r[i],r[j])) == 0):
                for k in range(3):
                    r[j][k] = 0

print(r)
r = np.asarray(r)
data = np.delete(r,np.where(~r.any(axis=1))[0], axis=0)
print(data)

[[1, 2, 3], [4, 5, 6], [0, 0, 0], [0, 0, 0], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
## METHOD 2 : WORKS FOR ANY ARRAY

r = [[1,2,3],
     [4,5,6],
     [1,2,3],
     [1,2,3],
     [7,8,9]]

for i in range(5):
    for j in range(5):
        if(i!=j):
            if(len(np.setdiff1d(r[i],r[j])) == 0):
                for k in range(len(r[j])):
                    r[j][k] = 0
idx = []
for i in range(5):
    count = 0
    for j in range(3):
        if r[i][j]==0:
            count+=1
    if count == 3:
        idx.append(i)

print(idx)
print(r)
r = np.asarray(r)
r_new = np.delete(r,idx,0)
print(r_new)

#data = np.delete(r,np.where(~r.any(axis=1))[0], axis=0)

[2, 3]
[[1, 2, 3], [4, 5, 6], [0, 0, 0], [0, 0, 0], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# METHOD 3 : OPTIMIZED VERSION OF PREVIOUS METHOD

r = [[1,2,3],
     [4,5,6],
     [1,2,3],
     [1,2,3],
     [7,8,9]]

idx = []
for i in range(5):
    for j in range(5):
        if(i!=j):
            if(len(np.setdiff1d(r[i],r[j])) == 0):
                for k in range(len(r[j])):
                    r[j][k] = 0
                idx.append(j)
idx = np.unique(idx)
print(idx)
print(r)
r = np.asarray(r)
r_new = np.delete(r,idx,0)
print(r_new)


[2 3]
[[1, 2, 3], [4, 5, 6], [0, 0, 0], [0, 0, 0], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
def issubset(a,b):
    return (len(np.setdiff1d(a,b)) == 0)
# if this returns true, then b is a subset of a or b itself is a(proper subset)
# in that case, remove b from clusters and keep a

In [23]:
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]
d = []
d = np.concatenate((d,a))
print(d)

[1. 2. 3.]


In [24]:
r = [[1,2,3],
     [4,5,6],
     [1,2,3],
     [1,2,3],
     [7,8,9]]

b = [10,11,12]
new = [[] for _ in range(5)]
for i in range(5):
    for j in range(3):
        new[i].append(r[i][j])
new.append(b)
print(new)
print(r)
r = new
print(r)

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [1, 2, 3], [7, 8, 9], [10, 11, 12]]
[[1, 2, 3], [4, 5, 6], [1, 2, 3], [1, 2, 3], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [1, 2, 3], [1, 2, 3], [7, 8, 9], [10, 11, 12]]
